version: "3"

services:
  ingryd-lms-ui:
    container_name: ingryd-lms-ui
    build:
      context: .
    restart: always
    ports:
      - 127.0.0.1:8080:3000
    command: npm run start
    env_file:
      - .env
