name: Dev CI/CD and Notification workflow

on:
  push:
    branches: [prod-release]

jobs:
  deploy-to-production:
    name: Deploy to prod
    runs-on: self-hosted
    steps:
      - name: Executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USERNAME }}
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          port: ${{ secrets.PROD_SSH_PORT }}
          script: |
            cd ~/ingryd-lms-landing-page

            sudo bash deploy.sh

            exit
