name: Dev CI/CD and Notification workflow for API

on:
  push:
    branches: [prod-release]

jobs:
  run-script:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 

      - name: Run Script
        run: |
          cd ~/ingryd-landing
          sudo bash deploy.sh
          exit
